const $=x=>document.getElementById(x),c=$('chart'),ctx=c.getContext('2d');let rows=[],idx=0,timer=null,marks=[],trades=[],pos=null,cache=new Map();
const fmt=t=>{let d=new Date(t),z=n=>String(n).padStart(2,'0');return `${d.getFullYear()}/${z(d.getMonth()+1)}/${z(d.getDate())} ${z(d.getHours())}:${z(d.getMinutes())}`};
const pk=t=>{let d=new Date(t);return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}`};
function months(a,b){let [y,m]=a.split('-').map(Number),[Y,M]=b.split('-').map(Number),r=[];while(y<Y||(y===Y&&m<=M)){r.push(`${y}-${String(m).padStart(2,'0')}`);if(++m>12){m=1;y++}}return r}
function parse(s){return s.split(/\r?\n/).map(x=>x.trim().split(',')).filter(p=>p.length>=6).map(p=>({t:Date.parse(p[0].replace(/\./g,'-')+'T'+p[1]+':00'),o:+p[2],h:+p[3],l:+p[4],c:+p[5]})).filter(x=>Number.isFinite(x.t)&&[x.o,x.h,x.l,x.c].every(Number.isFinite))}
async function get(m){if(cache.has(m))return cache.get(m);let r=await fetch('data/'+m+'.csv');if(!r.ok)throw Error(m+'.csv がありません');let x=parse(await r.text());cache.set(m,x);return x}
$('load').onclick=async()=>{stop();let s=new Date($('start').value).getTime(),e=new Date($('end').value).getTime();if(!Number.isFinite(s)||!Number.isFinite(e)||e<s)return $('status').textContent='日時を確認してください';try{$('status').textContent='CSV読み込み中...';let ks=months(pk(s),pk(e)),all=[];for(let m of ks)all.push(...await get(m));all.sort((a,b)=>a.t-b.t);rows=all.filter((x,i)=>x.t>=s&&x.t<=e&&(i===0||x.t!==all[i-1].t));idx=0;marks=[];trades=[];pos=null;$('slider').max=Math.max(0,rows.length-1);$('first').textContent=fmt(rows[0]?.t);$('last').textContent=fmt(rows.at(-1)?.t);$('status').textContent=rows.length.toLocaleString()+'本';draw();info();log()}catch(e){$('status').textContent='読み込み失敗: '+e.message}};
function visible(){return rows.slice(Math.max(0,idx-110),idx+1)}
function resize(){let d=devicePixelRatio||1,r=c.getBoundingClientRect();c.width=r.width*d;c.height=r.height*d;ctx.setTransform(d,0,0,d,0,0);draw()}window.onresize=resize;
function draw(){let w=c.clientWidth,h=c.clientHeight;ctx.clearRect(0,0,w,h);ctx.fillStyle='#090d12';ctx.fillRect(0,0,w,h);let a=visible();if(!a.length)return;let lo=Math.min(...a.map(x=>x.l)),hi=Math.max(...a.map(x=>x.h)),pad=(hi-lo)*.08||1;lo-=pad;hi+=pad;let py=v=>h-30-(v-lo)/(hi-lo)*(h-55),step=(w-70)/Math.max(a.length,1),first=idx-a.length+1;ctx.strokeStyle='#1b222a';for(let i=1;i<7;i++){let y=20+i*(h-50)/7;ctx.beginPath();ctx.moveTo(0,y);ctx.lineTo(w,y);ctx.stroke()}a.forEach((r,i)=>{let x=55+i*step+step/2;if($('showCandle').checked){ctx.strokeStyle=r.c>=r.o?'#d9dee5':'#929ca7';ctx.beginPath();ctx.moveTo(x,py(r.h));ctx.lineTo(x,py(r.l));ctx.stroke();ctx.fillStyle=r.c>=r.o?'#d9dee5':'#929ca7';ctx.fillRect(x-Math.max(1,step*.32),Math.min(py(r.o),py(r.c)),Math.max(2,step*.64),Math.max(1,Math.abs(py(r.c)-py(r.o))))}});if($('showLevels').checked){let r=rows[idx],d=new Date(r.t),day=d.getDate(),mon=d.getMonth(),yr=d.getFullYear();let prev=rows.filter(x=>{let q=new Date(x.t);return q.getFullYear()===yr&&q.getMonth()===mon&&q.getDate()===day-1});let lv={PDH:Math.max(...prev.map(x=>x.h)),PDL:Math.min(...prev.map(x=>x.l))};ctx.font='10px system-ui';for(let[n,v]of Object.entries(lv)){if(!Number.isFinite(v))continue;ctx.setLineDash([5,4]);ctx.strokeStyle='#59636e';ctx.beginPath();ctx.moveTo(55,py(v));ctx.lineTo(w-10,py(v));ctx.stroke();ctx.setLineDash([]);ctx.fillStyle='#aab3bd';ctx.fillText(n+' '+v.toFixed(2),4,py(v)-3)}}marks.forEach(m=>{let i=m-first;if(i>=0&&i<a.length){let r=a[i],x=55+i*step+step/2;ctx.fillStyle='#f0c85a';ctx.beginPath();ctx.arc(x,py(r.h)-10,4,0,7);ctx.fill()}});trades.forEach(t=>{let i=t.i-first;if(i>=0&&i<a.length){let r=a[i],x=55+i*step+step/2;ctx.fillStyle=t.side==='BUY'?'#49c78a':'#e36b73';ctx.font='bold 10px system-ui';ctx.fillText(t.side,x,py(t.side==='BUY'?r.l:r.h)+(t.side==='BUY'?15:-8))}})}
function info(){let r=rows[idx];if(!r)return;$('info').textContent=`${fmt(r.t)}  O ${r.o.toFixed(2)} H ${r.h.toFixed(2)} L ${r.l.toFixed(2)} C ${r.c.toFixed(2)}`;$('slider').value=idx;$('price').textContent=r.c.toFixed(2);if(pos){$('state').textContent=pos.side;$('entry').textContent=pos.p.toFixed(2);let p=pos.side==='BUY'?r.c-pos.p:pos.p-r.c;$('pnl').textContent=p.toFixed(2)}else{$('state').textContent='NO POSITION';$('entry').textContent='—';$('pnl').textContent='—'}}
function stop(){clearInterval(timer);timer=null;$('play').textContent='▶'}function play(){stop();$('play').textContent='⏸';timer=setInterval(()=>{if(idx<rows.length-1){idx++;info();draw()}else stop()},Math.max(16,1000/+$('speed').value))}$('play').onclick=()=>timer?stop():play();$('next').onclick=()=>{stop();if(idx<rows.length-1)idx++;info();draw()};$('back').onclick=()=>{stop();if(idx>0)idx--;info();draw()};$('slider').oninput=e=>{stop();idx=+e.target.value;info();draw()};
function enter(side){if(!rows[idx]||pos)return;pos={side,p:rows[idx].c,i:idx};trades.push({side,i:idx,p:pos.p,t:rows[idx].t});log();info();draw()}$('buy').onclick=()=>enter('BUY');$('sell').onclick=()=>enter('SELL');$('close').onclick=()=>{if(!pos)return;let r=rows[idx],p=pos,d=p.side==='BUY'?r.c-p.p:p.p-r.c;trades.push({side:'EXIT',i:idx,p:r.c,t:r.t,pnl:d});pos=null;log();info();draw()};
$('mark').onclick=()=>{if(rows[idx])marks.push(idx),draw()};$('delmark').onclick=()=>{marks.pop();draw()};$('clearmark').onclick=()=>{marks=[];draw()};function log(){$('log').innerHTML=trades.map(t=>`${fmt(t.t)}　${t.side}　${t.p.toFixed(2)} ${t.pnl==null?'':('損益 '+t.pnl.toFixed(2))}`).join('<br>')}
resize();
